### ISSUE TITLE
Add yourselves in the paper!

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy-0.2.0-paper#10]
Hey @yashrsharma44 @Bhavam @michiboo @vineetg3 @saurabh18213 @rohitsanj @Ankk98 @fiterace @arnav257 @mkhalid-s @Raahul-singh

I will appreciate if all of you can comment here:
Name:
Affiliation:
ORCID:

**Comment by shreyasbapat** [comment]
I will highly appreciate if you can find some time and do this! We are almost completing the paper!

**Comment by Raahul-Singh** [comment]
Name : Raahul Singh
Affiliation : Indian Institute of Information Technology, Sri City
ORCID : 0000-0003-4114-8856


Thanks!

**Comment by rohitsanj** [comment]
Sorry for the delay @shreyasbapat 

Name: Rohit Sanjay
Affiliation: Department of Electronics and Communication Engineering, Manipal Institute of Technology, Manipal, Karnataka
ORCID: 0000-0002-2981-6076

Thanks!

**Comment by mkhalid-s** [comment]
@shreyasbapat Apologies for the delay.

Name: Khalid Shaikh

Affiliation: Department of Computer Engineering, Yadavrao Taskgaonkar Institute of Engineering and Technology, Mumbai University, Mumbai, Maharashtra

ORCID: 0000-0002-6380-2815

Thanks 🙂

**Comment by Bhavam** [comment]
@shreyasbapat
Name-Bhavam Vidyarthi
Affiliation-Department of Electronics and Communication Engineering,Manipal Institute of Technology , Manipal, Karnataka
ORCID:0000-0002-6560-8864
Thank you for the opportunity.

**Comment by ritzvik** [comment]
@ShamanthNyk and @nimeshvashistha , please read the issue description and provide and details.

**Comment by ShamanthNyk** [comment]
@shreyasbapat 

Name: Shamanth R Nayak K
Affiliation: Department of Information and Communication Technology Engineering, Manipal Institute of Technology, Manipal, Karnataka
ORCID: 0000-0002-7159-8455

Thank you!!

**Comment by vineetg3** [comment]
Apologies for the Delay! @shreyasbapat 
Name: Vineet Gandham
Affiliation: Department of Computer Science and Engineering, Manipal Institute of Technology, Manipal, Karnataka
ORCID: 0000-0002-5704-3277

Thank you!

**Comment by nimeshvashistha** [comment]
@shreyasbapat 

Name: Nimesh Vashistha
Affiliation: Department of Electronics and Communication Engineering, Manipal Institute of Technology, Manipal, Karnataka
ORCID: 0000-0003-1079-381X

Thank You!

**Comment by arnav257** [comment]
Sorry for the delay.
Name: Arnav Das
Affiliation: Hiranandani Foundation, Powai, Mumbai
ORC-ID: 0000-0002-2716-7340

Thanks.

**Comment by ritzvik** [comment]
@Relativist1
Please read the issue description and do the needful

**Comment by Relativist1** [comment]
Name: Saurabh
Affiliation: Dyal Singh College, University of Delhi
ORDCID : 0000-0001-7156-4848

**Comment by gimseng** [comment]
Name: Gim Seng Ng
Affiliation: School of Mathematics and Hamilton Mathematics Institute, Trinity College Dublin, Dublin 2, Ireland
ORDCID : 0000-0003-1586-2538

**Comment by obi-wan-shinobi** [comment]
Name : Shreyas Kalvankar
Affiliation : K. K. Wagh Institute of Engineering Education and Research, Nashik, Maharashtra, India
ORDCID : 0000-0003-2380-424X

**Comment by GTron-1729** [comment]
Name : Ganesh Tarone
Affiliation : Department of Computer Engineering,Vishwakarma Institute of Technology,Pune, Maharashtra, India
ORCID : 0000-0002-1800-745X
